version: "3"

volumes:
  node_data: {}

networks:
  node-net:
    external: false

services:

  ################################ NODEjs ################################
    node-backend:
        image: node:12.10.0-alpine
        container_name: nodejs
        expose:
            - 5000
        environment:
            - REDIS_PORT=6379  
            - REDIS_HOST=redis
            - URL_API_TAKE=https://api.github.com/orgs/
        networks:
        - node-net
        restart: on-failure
        deploy:
          restart_policy:
            condition: on-failure
        ports:
            - 5000:5000
        volumes:
            - "./:/home/app/"
        depends_on:
        - redis
        links:
        - redis
        command: sh -c "cd /home/app && npm install --save && npm run start"

  ################################ REDIS ################################
    redis:
        image: redis:alpine
        container_name: redis
        expose:
            - 6379
        networks:
        - node-net  
        restart: on-failure
        deploy:
          restart_policy:
            condition: on-failure
        ports:
        - 6379:6379
        volumes:
            - ./config/redis.conf:/redis.conf
        command: [ "redis-server", "/redis.conf" ]