openapi: 3.0.0
info:
  description: >
    API respons치vel por realizar integra칞칚o com <b>GITHUB</b> </br>
    
    Retornando 5 reposit칩rios da linguagem C# da organiza칞칚o <b><font size="3" color="#00C6D7">Take</font></b>. </br>
    
    Ordenando pela data de cria칞칚o, dos mais antigos.</br>
     
    <font size="3" color="#839FD6"> Fun칞칫es extras </font></b> </br>
    - Caching </br>
    - Middlewares </br>
    
    
    <b><font size="3" color="#00C6D7"> <b>TAKE</font></b>
  title: "Get The Repositories"
  contact:
    name: Erlan Lucio
    url: https://github.com/lucioerlan
    email: "erlanlucio@hotmail.com"
  version: '1.0'
servers:
- url: http://localhost:5000/api
  variables: {}
paths:
  /get-repos-take:
    get:
      tags:
      - ROUTES
      summary: GET REPOS TAKE
      operationId: GETREPOSTAKE
      parameters: []
      responses:
        '200':
          description: '游녤  Rota respons치vel, por retornar 5 reposit칩rios da linguagem C# da organiza칞칚o Take. Ordenando pela data de cria칞칚o, dos mais antigos'
          headers: {}
      deprecated: false
tags:
- name: ROUTES
